name: Install Python Dependencies
description: "Installs Python dependencies for the project."
inputs:
  python-version:
    required: true
    description: "The Python version to install dependencies for."
  gh-token:
    required: true
    description: "The GitHub token to use for authentication."

runs:
  using: composite
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Multivenv
      shell: bash
      run: pip install multivenv
    - name: Install Just command runner
      uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
    - id: get-requirements-path
      shell: bash
      run: |
        reqs_extension=$(python reqs_extension.py)
        echo "::set-output name=requirements-extension::$reqs_extension"
        echo "Will cache requirements files with extension $reqs_extension"
    - uses: actions/cache@v3
      id: cache-venvs
      name: Cache venvs
      with:
        path: venvs
        key: ${{ env.pythonLocation }}-venvs-v2-${{ hashFiles(format('requirements/*-requirements{0}.txt', steps.get-requirements-path.outputs.requirements-extension)) }}
    - name: Create venvs
      shell: bash
      if: steps.cache-venvs.outputs.cache-hit != 'true'
      run: |
        mvenv sync
