[tool.poetry]
name = "flexlate-dev-lint"
description = "Linting for flexlate-dev"
version = "1.0.0"
authors = ["Nick DeRobertis <derobertis.nick@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
flexlate-dev = {path = "../..", develop = true}
flake8 = "*"
mypy = "*"